title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://seotorm.github.io

aux_links:
  Template Repository: https://github.com/seotorm/seotorm.github.io

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.6"

# Enable or disable heading anchors
heading_anchors: true

# Color scheme supports "light" (default) and "dark"
color_scheme: light


# Footer content
# appears at the bottom of every page's main content
# Note: The footer_content option is deprecated and will be removed in a future major release. Please use `_includes/footer_custom.html` for more robust
footer_content: "Footer"